plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme

url: https://ucsb-cs56.github.io # the base hostname & protocol for your site
baseurl: /  # the subpath of your site, e.g. "/blog"

course: "CS156"
title: "UCSB CS156"
github_url: https://github.com/ucsb-cs156/ucsb-cs156.github.io

on_campus: http://proquest.safaribooksonline.com
off_campus: http://proquest.safaribooksonline.com.proxy.library.ucsb.edu:2048/
hfj_url: book/programming/java/0596009208
jn7_url: book/programming/java/9781492037248
hfdp_url: book/software-engineering-and-development/patterns/0596007124 

exclude: ['vendor', 'setup.sh', 'jekyll.sh']

timezone: America/Los_Angeles

collections:
  topics:
    output: true
    permalink: /topics/:path/
    
  tutorials:
    output: true
    permalink: /tutorials/:path/


  textbooks:
    output: true
    permalink: /textbooks/:path/
    used_this_quarter: true

  hfj:
    output: true
    permalink: /hfj/:path/

  jn7:
    output: true
    permalink: /jn7/:path/


  hfdp:
    output: true
    permalink: /hfdp/:path/
    
  resources:
    output: true
    permalink: /resources/:path/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: pages
    values:
      layout: "default"

  - scope:
      path: ""
      type: topics
    values:
      layout: default
      
  - scope:
      path: ""
      type: tutorials
    values:
      layout: tutorial
      
  - scope:
      path: ""
      type: hfj
    values:
      layout: chapter

  - scope:
      path: ""
      type: jn7
    values:
      layout: chapter

  - scope:
      path: ""
      type: hfdp
    values:
      layout: chapter
      
  - scope:
      path: ""
      type: resources
    values:
      layout: default

include:
  - _pages
exclude: [vendor]

head_scripts:
   - /static/js/select_section.js
   - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML
